name: 'Setup Misc Configs'
description: 'Configure miscellaneous kernel options'

runs:
  using: composite
  steps:
    - name: 'Apply Misc Kernel Configs'
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          CONFIG_OVERLAY_FS=y
          CONFIG_TMPFS_XATTR=y
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_KALLSYMS=y
          CONFIG_KALLSYMS_ALL=y
