name: 'Apply Unicode Fix Patch'
description: 'Apply unicode bypass fix patch for kernel 6.6'

inputs:
  kernel_version:
    description: 'Kernel version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Apply Unicode Fix Patch
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        set -euo pipefail

        KERNEL_VERSION="${{ inputs.kernel_version }}"

        echo "Patching unicode for kernel ${KERNEL_VERSION}!"

        patch -p1 --forward < \
          "${{ github.workspace }}/kernel_patches/common/unicode_bypass_fix_6.1+.patch"
