name: Kernel Name Branding
description: Applies kernel name branding

inputs:
  version:
    description: Android kernel version (e.g. android15-6.6)
    required: true
  sublevel:
    description: Kernel sublevel
    required: false
    default: 87

runs:
  using: composite
  steps:
    - name: Apply Kernel Branding
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      env:
        VERSION: ${{ inputs.version }}
        SUBLEVEL: ${{ inputs.sublevel }}
      run: |
        readonly SCM_COUNT=8
        readonly GIT_HASH=88d70c0b44bf
        readonly BUILD_NUM=14541233
        readonly PAGE_SIZE=4k

        ANDROID_VERSION="${VERSION%%-*}"
        KERNEL_VERSION="${VERSION#*-}"

        case "$VERSION" in
          android15-6.6|android16-6.12)
            KERNEL_STRING="${KERNEL_VERSION}.${SUBLEVEL}-${ANDROID_VERSION}"
            ;;
          *)
            KERNEL_STRING="-${ANDROID_VERSION}"
            ;;
        esac

        FULL_STRING="${KERNEL_STRING}-${SCM_COUNT}-g${GIT_HASH}-ab${BUILD_NUM}-${PAGE_SIZE}"

        {
          sed '$d' scripts/setlocalversion
          printf 'echo "%s"\n' "$FULL_STRING"
        } > scripts/setlocalversion.tmp

        mv scripts/setlocalversion.tmp scripts/setlocalversion
        chmod +x scripts/setlocalversion
