name: 'Apply NTSync Patches'
description: 'Apply ntsync compatibility patches and enable CONFIG_NTSYNC in defconfig'
inputs:
  version:
    description: 'Kernel config version (e.g., android14-6.12)'
    required: true
  kernel_version:
    description: 'Kernel version (e.g., 6.1)'
    required: true
  sublevel:
    description: 'Kernel sublevel'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Apply NTSync Patch
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      run: |
        set -euo pipefail

        patch -p1 < ${{ github.workspace }}/kernel_patches/common/ntsync/ntsync_compat_${{ inputs.version }}.patch
        patch -p1 < ${{ github.workspace }}/kernel_patches/common/ntsync/ntsync_base.patch

    - name: Enable NTSync
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          CONFIG_NTSYNC=y
